name: slow blog
description:
meta_description: "a blog about cinematography, gaming, storytelling, lighting, tech"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog
domain_name: "http://polyrhythm.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Ryan Jones"

# Disqus config
disqus-shortname: ""
